### PR TITLE
Problem (Fix #349): missing display for tx failures

### LINKED ISSUE #349: Problem: missing display for tx failures
image

for example)
redelegation failure is quite common
```
Tx Failed
failed to execute message; message index: 0: redelegation to this validator already in progress; first redelegation to this validator must complete before next redelegation
```

display the cause of tx failures.

and for other common types,
incorrect sequence number

i suggest broadcastResponse contents is displayed to the user.
```
 const broadcastResponse = await this.client.broadcastTx(signedBytes);
      // eslint-disable-next-line no-console
      console.log(`tx failure= ${JSON.stringify(broadcastResponse)}`);
      if (isBroadcastTxFailure(broadcastResponse)) {
        // noinspection ExceptionCaughtLocallyJS
        throw new TypeError(`Transaction failed: ${JSON.stringify(broadcastResponse)}`);
      }
```

### PR DESCRIPTION
**Pull request by crypto-matto**
螢幕截圖 2021-03-29 下午1 01 34
螢幕截圖 2021-03-29 下午1 01 19
螢幕截圖 2021-03-29 下午1 00 50

### CODE REVIEW

File: src/pages/home/home.tsx [hunk 1]
```diff
@@ -613,8 +614,12 @@ function HomePage() {
             <>
               <div className="description">
                 {delegationActionType === StakingActionType.UNDELEGATE
-                  ? 'The undelegation transaction failed. Please try again later'
-                  : 'The redelegation transaction failed. Please try again later'}
+                  ? 'The undelegation transaction failed. Please try again later.'
+                  : 'The redelegation transaction failed. Please try again later.'}
+                <br />
+                {errorMessages.map((err, idx) => (
```
Comment (eddycpc) [inline src/pages/home/home.tsx:620]: We can make the array filtering for distinct values so that we don't have the same error showing more than once, like the one in the first screenshot

**Review by eddycpc — CHANGES_REQUESTED** [review]

**Review by eddycpc — COMMENTED** [review]
Good work!

**Review by eddycpc — APPROVED** [review]
