### PR TITLE
Problem: Support self destruction on N incorrect attempts

### LINKED ISSUE #700: Problem: Support self-destruct user session after `N` incorrect attempts

### PR DESCRIPTION
**Pull request by cdc-Hitesh**
Fixes #700

### CODE REVIEW

File: src/components/PasswordForm/PasswordFormModal.tsx [hunk 1]
```diff
@@ -126,7 +141,16 @@ const PasswordFormModal: React.FC<PasswordFormModalProps> = props => {
           {validationErrMsg ? (
             <div>
               <ErrorXmark />
-              <div className="result-message">{validationErrMsg}</div>
+              <div className="result-message">{
+              validationErrMsg
+              .includes('*break*')?  
+              validationErrMsg
+              .split('*break*')
```
Comment (crypto-3dd) [inline src/components/PasswordForm/PasswordFormModal.tsx:148]: Not sure I'm following up the logic happening around this section

**Review by crypto-3dd — APPROVED** [review]
